# Generated by Django 5.2.9 on 2025-12-02 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_post_customer_post_user_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='min_age',
        ),
    ]
